language: php
sudo: false

before_script: "sh bin/travis-init.sh"

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

services:
    - memcached

matrix:
  allow_failures:
    - php: 7.0
    - php: hhvm
